### ISSUE TITLE
What's the difference with JuliaSparse/Pardiso.jl ?

### ISSUE THREAD

**Issue by aminya** [fverdugo/PardisoMKL.jl#1]
What's the difference of this repo with https://github.com/JuliaSparse/Pardiso.jl ?

**Comment by fverdugo** [comment]
PardisoMKL.jl provides access to the low level FORTRAN subroutines of Intel MKL Pardiso, whereas Pardiso.jl provides a more high level and more user-friendly interface to the Pardiso solvers (but it does not provide access to the low level FORTRAN subroutines).

I hope that the low level routines of PardisoMKL.jl are included into Pardiso.jl in the future, but I cannot guarantee this since I am not the maintainer of Pardiso.jl...

I hope this answer clarifies your question.
